#!/usr/bin/env node

var fs = require("fs"),
	compiler = require("jstpl").compiler(),
	argv = require('optimist')["default"]({"function": "jstpl"}).argv,
	out = function(s) { process.stdout.write(s) };

if(argv.out) {
	out = function(s) {
		fs.writeFileSync(argv.out, s)
	}
}

if(argv.plugins != "no") {
	compiler.loadPlugins()
}

for(var i in argv._)
	compiler.parse(argv._[i])

compiler.getCode(function(err, code) {
	if(err)
		throw err
	else
		out("var " + argv.function + " = " + code + ";")
})

