#!/usr/bin/env node

var fs = require("fs"),
	compiler = require("js_tpl").compiler(), //require("js_tpl").compiler(),
	argv = require('optimist')["default"]({"function": "tpl2js"}).argv,
	out = function(s) { process.stdout.write(s) };

if(argv.out) {
	out = function(s) {
		fs.writeFileSync(argv.out, s)
	}
}

if(argv.plugins != "no") {
	compiler.loadDefaultPlugins()
}

for(var i in argv._)
	compiler.parseFile(argv._[i])

compiler.getCode(function(err, code) {
	if(err)
		throw err
	else
		out("var " + argv.function + " = " + code + ";")
})

